# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import csv
import ezdxf
from ezdxf.enums import TextEntityAlignment
from ezdxf import zoom

RESOURCES_PATH = os.path.dirname(__file__).replace("py_components", "resources")

inputpic = os.path.join(RESOURCES_PATH, "picture.JPG")


class Ui_CPT_CSV_TO_DXF(object):
    def setupUi(self, CPT_CSV_TO_DXF):
        CPT_CSV_TO_DXF.setObjectName("CPT_CSV_TO_DXF")
        CPT_CSV_TO_DXF.resize(722, 827)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CPT_CSV_TO_DXF)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.import_csv_bttn = QtWidgets.QPushButton(CPT_CSV_TO_DXF)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.import_csv_bttn.setFont(font)
        self.import_csv_bttn.setObjectName("import_csv_bttn")
        self.verticalLayout.addWidget(self.import_csv_bttn)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.name_label = QtWidgets.QLabel(CPT_CSV_TO_DXF)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout_4.addWidget(self.name_label)
        self.name_field_lineedit = QtWidgets.QLineEdit(CPT_CSV_TO_DXF)
        self.name_field_lineedit.setObjectName("name_field_lineedit")
        self.horizontalLayout_4.addWidget(self.name_field_lineedit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.height_label = QtWidgets.QLabel(CPT_CSV_TO_DXF)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.height_label.setFont(font)
        self.height_label.setObjectName("height_label")
        self.horizontalLayout_5.addWidget(self.height_label)
        self.height_field_lineedit = QtWidgets.QLineEdit(CPT_CSV_TO_DXF)
        self.height_field_lineedit.setObjectName("height_field_lineedit")
        self.horizontalLayout_5.addWidget(self.height_field_lineedit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.frame_3 = QtWidgets.QFrame(CPT_CSV_TO_DXF)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout.addWidget(self.frame_3)
        self.export_qc_bttn = QtWidgets.QPushButton(CPT_CSV_TO_DXF)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.export_qc_bttn.setFont(font)
        self.export_qc_bttn.setObjectName("export_qc_bttn")
        self.verticalLayout.addWidget(self.export_qc_bttn)
        self.frame_2 = QtWidgets.QFrame(CPT_CSV_TO_DXF)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        self.export_rf_bttn = QtWidgets.QPushButton(CPT_CSV_TO_DXF)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.export_rf_bttn.setFont(font)
        self.export_rf_bttn.setObjectName("export_rf_bttn")
        self.verticalLayout.addWidget(self.export_rf_bttn)
        self.frame_4 = QtWidgets.QFrame(CPT_CSV_TO_DXF)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.Picture_label = QtWidgets.QLabel(CPT_CSV_TO_DXF)
        self.Picture_label.setText("")
        self.Picture_label.setPixmap(QtGui.QPixmap(inputpic))
        self.Picture_label.setObjectName("Picture_label")
        self.horizontalLayout_2.addWidget(self.Picture_label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(CPT_CSV_TO_DXF)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(CPT_CSV_TO_DXF)
        QtCore.QMetaObject.connectSlotsByName(CPT_CSV_TO_DXF)

    def retranslateUi(self, CPT_CSV_TO_DXF):
        _translate = QtCore.QCoreApplication.translate
        CPT_CSV_TO_DXF.setWindowTitle(_translate("CPT_CSV_TO_DXF", "Dialog"))
        self.import_csv_bttn.setText(_translate("CPT_CSV_TO_DXF", "CSV file beolvasása"))
        self.name_label.setText(_translate("CPT_CSV_TO_DXF", "Feltárás neve:"))
        self.height_label.setText(_translate("CPT_CSV_TO_DXF", "Feltárás magassága:"))
        self.export_qc_bttn.setText(_translate("CPT_CSV_TO_DXF", "qc görbe rajzolása"))
        self.export_rf_bttn.setText(_translate("CPT_CSV_TO_DXF", "Rf görbe rajzolása"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CPT_CSV_TO_DXF = QtWidgets.QDialog()
    ui = Ui_CPT_CSV_TO_DXF()
    ui.setupUi(CPT_CSV_TO_DXF)
    CPT_CSV_TO_DXF.show()
    sys.exit(app.exec_())
